services:
  # Core Infrastructure Services
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    environment:
      TZ: America/Denver
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_DB: weatherflow
      INFLUXDB_HTTP_FLUX_ENABLED: true
      INFLUXDB_USER: weatherflow
      INFLUXDB_USER_PASSWORD: "${WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD}"
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb:rw

  influxdb2:
    container_name: influxdb2
    image: influxdb:latest
    volumes:
      - ./data/influxdb2:/var/lib/influxdb2:rw
    env_file:
      - weatherflow_collector_v2.env
      - weatherflow_collector_v2.dev
    ports:
      - "8087:8086"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  grafana:
    container_name: grafana
    build: ./grafana
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      TZ: America/Denver
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mosquitto:/etc/mosquitto
      - ./data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf