{
 "title": "Rivian",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "latitude = from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rivian\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Latitude\")\nlongitude = from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rivian\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Longitude\")\nunion(tables: [latitude, longitude])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "title": "Charge End",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Charge End\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Charge Elapsed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and r._field == \"Charge Elapsed\")\n  |> map(fn: (r) => ({ r with _value: r._value / 60.0 }))  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Charge Session",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and r._field == \"Charge Session\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Battery\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    },
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n  r._field == \"Battery Limit\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    }
   ]
  },
  {
   "title": "Cabin Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and r._field == \"Cabin Temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    },
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and r._field == \"Cabin Temp\")\n  |> map(fn: (r) => ({ r with _value: (r._value * (9.0 / 5.0)) + 32.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Power\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    },
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Drive Mode\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    },
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Gear\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Charge State\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    },
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Charger Status\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Range\" or r._field == \"Battery\" or r._field == \"Battery Limit\" or r._field == \"Charge Power\" or r._field == \"Cabin Temp\" or r._field == \"Charge Session\"\n  )\n  |> drop(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)  "
    }
   ]
  },
  {
   "title": "# DC Charges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "threshold = 20\n\nfrom(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rivian\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Charge Power\")\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> stateCount(fn: (r) => r._value > threshold, column: \"charge_sessions\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _total: if r.charge_sessions == 1 then 1 else 0\n    })\n  )\n  |> sum(column: \"_total\")",
     "select": [
      [
       { "params": [ "Charge Power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Battery over 50%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "over_threshold",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Battery::field", "operator": ">", "value": "50" }
     ]
    },
    {
     "alias": "total",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Battery over 60%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "over_threshold",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Battery::field", "operator": ">", "value": "60" }
     ]
    },
    {
     "alias": "total",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Battery over 70%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "over_threshold",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Battery::field", "operator": ">", "value": "70" }
     ]
    },
    {
     "alias": "total",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Battery over 80%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "over_threshold",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Battery::field", "operator": ">", "value": "80" }
     ]
    },
    {
     "alias": "total",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Battery over 90%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "over_threshold",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Battery::field", "operator": ">", "value": "90" }
     ]
    },
    {
     "alias": "total",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Range @ 100",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Battery\"\n  )\n  |> drop(columns:[\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)  "
    },
    {
     "query": "battery = from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rivian\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Battery\")\nrangee = from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rivian\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Range\")\nunion(tables: [battery, rangee])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.Range / r.Battery * 100.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)  \n  |> drop(columns: [\"Battery\", \"Range\", \"_stop\", \"_start\", \"_measurement\"])\n  |> rename(columns: {\"_value\": \"Estimated Range @ 100\"})"
    },
    {
     "query": "from(bucket: \"rivian\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and\n    r._field == \"Mileage\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)  "
    }
   ]
  }
 ]
}