from os import environ

INFLUXDB_V1_URL = "influxdb"
INFLUXDB_V1_USER = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME")
INFLUXDB_V1_PASS = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD")

INFLUXDB_V2_URL = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_URL")
INFLUXDB_V2_TOKEN = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_TOKEN")
INFLUXDB_V2_ORG = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_ORG")


PUSHOVER_USER = environ.get("PUSHOVER_USER")
PUSHOVER_SPRINKLER_TOKEN = environ.get("PUSHOVER_SPRINKLER_TOKEN")