from os import environ

INFLUXDB_URL = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_URL")
INFLUXDB_USER = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME")
INFLUXDB_PASS = environ.get("WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD")
